services:
  authorization-service:
    path: authorization-service

  product-service:
    path: product-service

  import-service:
    path: import-service
    params:
      SQSQueueArn: ${product-service.SQSQueueArn}
      SQSUrl: ${product-service.SQSUrl}
